// let the routes generated by koa-router and koa-resource-router to be in the same JSON format :-D
module.exports = function unify (router) {

  var point = {
    name : "",
    routes : []
  }
  
  if (router.name) {
    point.name = router.name;

    router.routes.forEach(function(route){
      route.regexp = route.regexp.toString();
      point.routes.push(route);
    });

  }
  else {
    router.routes.forEach(function(route){
      
      point.name = route.name;

      var i = route.methods.length;

      while (i--) {
        point.routes.push({
          url : route.path,
          method : route.methods[i],
          regexp : route.regexp.toString(),
          params : route.params
        });
      }
    });
  }
  return point;
}